---
- name: install packages
  hosts: all
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: present
  - name:
    service:
      name: httpd
      state: started
    
